const modifiers: Rule = {
  children: {
    aggressive: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    ai: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    air: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    army: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    autonomy: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    country: { 
      type: Value.UNQUOTED, 
      cardinality: [0, "inf"],
      children: {
        air_advisor_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        air_carrier_night_penalty_reduction_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        air_chief_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        air_doctrine_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        air_home_defence_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        air_power_projection_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        air_untrained_pilots_penalty_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        air_wing_xp_loss_when_killed_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        aircraft_manufacturer_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        army_attack_against_major_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        army_attack_speed_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        army_chief_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        army_strength_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        choose_preferred_tactics_cost: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        command_abilities_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        command_cap: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        coordination_bonus: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        economy_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        exiled_government_weekly_manpower: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        high_command_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        industrial_concern_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        intel_from_combat_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        land_doctrine_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        materiel_manufacturer_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        mobilization_laws_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        naval_doctrine_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        naval_invasion_planning_bonus_speed: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        naval_manufacturer_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        naval_night_attack: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        naval_retreat_chance_after_initial_combat: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        naval_retreat_speed_after_initial_combat: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        navy_chief_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        navy_weather_penalty: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        night_spotting_chance: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        org_loss_at_low_org_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        party_popularity_stability_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        political_advisor_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        railway_gun_bombardment_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        screening_without_screens: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        supply_combat_penalties_on_core_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        tank_manufacturer_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        terrain_trait_xp_gain_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        theorist_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        trade_laws_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        unit_leader_as_advisor_cp_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        cat_mobile_warfare_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        cat_superior_firepower_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        cat_grand_battle_plan_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        cat_mass_assault_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        cat_strategic_destruction_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        cat_battlefield_support_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        cat_operational_integrity_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        cat_base_strike_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        cat_fleet_in_being_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        cat_trade_interdiction_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        army_leader_start_level: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        navy_leader_start_level: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        army_leader_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        navy_leader_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        military_leader_cost_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        army_leader_start_attack_level: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        army_leader_start_defense_level: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        army_leader_start_logistics_level: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        army_leader_start_planning_level: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        navy_leader_start_attack_level: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        navy_leader_start_coordination_level: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        navy_leader_start_defense_level: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        navy_leader_start_maneuvering_level: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
      }
    },
    defensive: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    government_in_exile: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    intelligence_agency: { 
      type: Value.UNQUOTED, 
      cardinality: [0, "inf"],
      children: {
        operation_risk: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        operation_cost: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        operation_outcome: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        operation_infiltrate_risk: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        operation_infiltrate_cost: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        operation_infiltrate_outcome: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        operation_steal_tech_risk: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        operation_steal_tech_cost: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        operation_steal_tech_outcome: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        target_sabotage_risk: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        target_sabotage_cost: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        target_sabotage_outcome: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
      }
    },
    military_advancements: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    naval: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    peace: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    politics: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    state: { 
      type: Value.UNQUOTED, 
      cardinality: [0, "inf"],
      children: {
        army_attack_speed_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        supply_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        truck_attrition_factor: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        attrition_for_controller: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        enemy_operative_detection_chance: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
        enemy_operative_detection_chance_over_occupied_tag: { type: Value.UNQUOTED, cardinality: [0, 1], defaultValue: false },
      }
    },
    unit_leader: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    war_production: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
  },
};