const country: Rule = {
  children: {
    targeted_modifier_rule: {
      provide: { context: Context.TARGETED_MODIFIER, scope: Scope.COUNTRY },
      cardinality: [0, "inf"],
      children: {
        tag: { type: Value.UNQUOTED },
        alias_name: { type: Value.UNQUOTED },
      },
    },
    modifier_rule: {
      provide: { context: Context.MODIFIER, scope: Scope.COUNTRY },
      cardinality: [0, "inf"],
      children: {
        enum: { type: Value.UNQUOTED },
        alias_name: { type: Value.UNQUOTED },
      },
    },
    modifier: [
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { provide: { context: Context.MODIFIER, scope: Scope.COUNTRY } },
      { type: Value.UNQUOTED }
    ],
    unit_stat: [
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { provide: { context: Context.UNIT_STAT, scope: Scope.COUNTRY } },
      { provide: { context: Context.UNIT_STAT, scope: Scope.COUNTRY } },
      { provide: { context: Context.UNIT_STAT, scope: Scope.COUNTRY } },
      { provide: { context: Context.UNIT_STAT, scope: Scope.COUNTRY } },
      { provide: { context: Context.UNIT_STAT, scope: Scope.COUNTRY } }
    ],
    naval_stat: { type: Value.UNQUOTED },
    air_stat: { type: Value.UNQUOTED },
    unit_leader_modifier: [
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED, cardinality: [0, 1] },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { type: Value.UNQUOTED },
      { provide: { context: Context.UNIT_STAT, scope: Scope.COUNTRY } },
      { provide: { context: Context.UNIT_STAT, scope: Scope.COUNTRY } },
      { provide: { context: Context.UNIT_STAT, scope: Scope.COUNTRY } },
      { provide: { context: Context.UNIT_STAT, scope: Scope.COUNTRY } }
    ],
  },
};