const values: Rule = {
  children: {
    date: { type: Value.UNQUOTED },
    num_days: { type: Value.UNQUOTED },
    year: { type: Value.UNQUOTED },
    difficulty: { type: Value.UNQUOTED },
    threat: { type: Value.UNQUOTED },
    ai_attitude_allied_weight: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_attitude_friendly_weight: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_attitude_hostile_weight: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_attitude_is_threatened: { type: Value.UNQUOTED },
    ai_attitude_neutral_weight: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_attitude_outraged_weight: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_attitude_protective_weight: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_attitude_threatened_weight: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_attitude_wants_ally: { type: Value.UNQUOTED },
    ai_attitude_wants_antagonize: { type: Value.UNQUOTED },
    ai_attitude_wants_ignore: { type: Value.UNQUOTED },
    ai_attitude_wants_protect: { type: Value.UNQUOTED },
    ai_attitude_wants_weaken: { type: Value.UNQUOTED },
    ai_desire_resource: { type: Value.UNQUOTED },
    ai_strategy_activate_crypto: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_alliance: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_antagonize: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_befriend: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_conquer: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_consider_weak: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_contain: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_declare_war: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_decrypt_target: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_dont_defend_ally_borders: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_force_defend_ally_borders: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_ignore: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_ignore_claim: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_influence: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_invade: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_occupation_policy: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_prepare_for_war: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_protect: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_send_volunteers_desire: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ai_strategy_support: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    air_intel: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    ambition_area_enum: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    army_experience: { type: Value.UNQUOTED },
    army_intel: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    autonomy_ratio: { type: Value.UNQUOTED },
    capital: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    civilian_intel: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    command_power: { type: Value.UNQUOTED },
    core_compliance: { type: Value.UNQUOTED },
    core_resistance: { type: Value.UNQUOTED },
    cryptology_defense_level: { type: Value.UNQUOTED },
    current_party_ideology_group: { type: Value.UNQUOTED },
    days_mission_timeout: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    decryption_speed: { type: Value.UNQUOTED },
    encryption_strength: { type: Value.UNQUOTED },
    faction_leader: { type: Value.UNQUOTED },
    fuel_k: { type: Value.UNQUOTED },
    garrison_equipment_support_ratio: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    highest_party_ideology: {
      type: Value.UNQUOTED,
      cardinality: [0, "inf"],
      provide: { context: Context.EXCLUDE_RULING_PARTY, scope: null },
    },
    highest_party_popularity: {
      type: Value.UNQUOTED,
      cardinality: [0, "inf"],
      provide: { context: Context.EXCLUDE_RULING_PARTY, scope: null },
    },
    host: { type: Value.UNQUOTED },
    id: { type: Value.UNQUOTED },
    legitimacy: { type: Value.UNQUOTED },
    manpower: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    manpower_k: { type: Value.UNQUOTED },
    max_available_manpower: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    max_available_manpower_k: { type: Value.UNQUOTED },
    max_manpower: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    max_manpower_k: { type: Value.UNQUOTED },
    deployed_manpower_k: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    navy_experience: { type: Value.UNQUOTED },
    navy_intel: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    num_armies: { type: Value.UNQUOTED },
    num_armies_in_state: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    num_armies_with_type: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    num_battalions: { type: Value.UNQUOTED },
    num_battalions_with_type: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    num_controlled_states: { type: Value.UNQUOTED },
    num_core_states: { type: Value.UNQUOTED },
    num_deployed_planes: { type: Value.UNQUOTED },
    num_deployed_planes_with_type: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    num_equipment: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    num_equipment_in_armies: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    num_equipment_in_armies_k: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    num_owned_controlled_states: { type: Value.UNQUOTED },
    num_owned_states: { type: Value.UNQUOTED },
    num_ships: { type: Value.UNQUOTED },
    num_ships_with_type: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    num_target_equipment_in_armies: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    num_target_equipment_in_armies_k: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    opinion: {
      cardinality: [0, "inf"],
      provide: [
        { context: Context.SCOPE, scope: Scope.COUNTRY },
        { context: Context.ENUM, scope: Scope.COUNTRY_TAGS },
        { context: Context.ROOT, scope: null },
        { context: Context.FROM, scope: null },
        { context: Context.PREV, scope: null },
        { context: Context.THIS, scope: null },
      ],
    },
    original_tag: { type: Value.UNQUOTED },
    overlord: { type: Value.UNQUOTED },
    party_popularity: {
      type: Value.UNQUOTED,
      cardinality: [0, "inf"],
      provide: [{ context: Context.IDEOLOGY, scope: null }, { context: Context.RULING_PARTY, scope: null }],
    },
    political_power: { type: Value.UNQUOTED },
    resource: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    stability: { type: Value.UNQUOTED },
    ai_irrationality: { type: Value.UNQUOTED },
    ai_wants_divisions: { type: Value.UNQUOTED },
    alliance_naval_strength_ratio: { type: Value.UNQUOTED },
    alliance_strength_ratio: { type: Value.UNQUOTED },
    amount_manpower_in_deployment_queue: { type: Value.UNQUOTED },
    amount_research_slots: { type: Value.UNQUOTED },
    any_war_score: { type: Value.UNQUOTED },
    casualties: { type: Value.UNQUOTED },
    casualties_k: { type: Value.UNQUOTED },
    command_power_daily: { type: Value.UNQUOTED },
    compare_autonomy_progress_ratio: { type: Value.UNQUOTED },
    conscription_ratio: { type: Value.UNQUOTED },
    convoy_threat: { type: Value.UNQUOTED },
    current_conscription_amount: { type: Value.UNQUOTED },
    days_since_capitulated: { type: Value.UNQUOTED },
    decryption_progress: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    enemies_naval_strength_ratio: { type: Value.UNQUOTED },
    enemies_strength_ratio: { type: Value.UNQUOTED },
    foreign_manpower: { type: Value.UNQUOTED },
    fuel_ratio: { type: Value.UNQUOTED },
    garrison_manpower_need: { type: Value.UNQUOTED },
    has_added_tension_amount: { type: Value.UNQUOTED },
    has_collaboration: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    has_legitimacy: { type: Value.UNQUOTED },
    has_manpower: { type: Value.UNQUOTED },
    has_political_power: { type: Value.UNQUOTED },
    has_stability: { type: Value.UNQUOTED },
    has_war_support: { type: Value.UNQUOTED },
    land_doctrine_level: { type: Value.UNQUOTED },
    manpower_per_military_factory: { type: Value.UNQUOTED },
    mine_threat: { type: Value.UNQUOTED },
    network_national_coverage: {
      cardinality: [0, "inf"],
      provide: [{ context: Context.SCOPE, scope: Scope.COUNTRY }, { context: Context.ENUM, scope: Scope.COUNTRY_TAGS }],
    },
    num_divisions: { type: Value.UNQUOTED },
    num_faction_members: { type: Value.UNQUOTED },
    num_fake_intel_divisions: { type: Value.UNQUOTED },
    num_free_operative_slots: { type: Value.UNQUOTED },
    num_occupied_states: { type: Value.UNQUOTED },
    num_of_available_civilian_factories: { type: Value.UNQUOTED },
    num_of_available_military_factories: { type: Value.UNQUOTED },
    num_of_available_naval_factories: { type: Value.UNQUOTED },
    num_of_civilian_factories: { type: Value.UNQUOTED },
    num_of_civilian_factories_available_for_projects: { type: Value.UNQUOTED },
    num_of_controlled_factories: { type: Value.UNQUOTED },
    num_of_controlled_states: { type: Value.UNQUOTED },
    num_of_factories: { type: Value.UNQUOTED },
    num_of_military_factories: { type: Value.UNQUOTED },
    num_of_naval_factories: { type: Value.UNQUOTED },
    num_of_nukes: { type: Value.UNQUOTED },
    num_of_operatives: { type: Value.UNQUOTED },
    num_operative_slots: { type: Value.UNQUOTED },
    num_of_owned_factories: { type: Value.UNQUOTED },
    num_researched_technologies: { type: Value.UNQUOTED },
    num_subjects: { type: Value.UNQUOTED },
    num_tech_sharing_groups: { type: Value.UNQUOTED },
    original_research_slots: { type: Value.UNQUOTED },
    political_power_daily: { type: Value.UNQUOTED },
    political_power_growth: { type: Value.UNQUOTED },
    surrender_progress: { type: Value.UNQUOTED },
    target_conscription_amount: { type: Value.UNQUOTED },
    total_constructed: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    total_equipment_produced: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    controller: { type: Value.UNQUOTED },
    owner: { type: Value.UNQUOTED },
    arms_factory_level: { type: Value.UNQUOTED },
    building_level: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    damaged_building_level: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    distance_to: { type: Value.UNQUOTED, cardinality: [0, "inf"] },
    industrial_complex_level: { type: Value.UNQUOTED },
    infrastructure_level: { type: Value.UNQUOTED },