// Some variables has the initial set of items
// Arrays declared here will be registered on the validator initialization

export const ai_roles = [
  "infantry",
  "anti_tank",
  "artillery",
  "bicycle_battalion",
  "cavalry",
  "garrison",
  "marines",
  "mechanized",
  "militia",
  "mobile",
  "motorized",
  "mountaineers",
  "paratroopers",
  "suppression",
  "fake_intel_unit",
  "armor",
  "light_armor",
  "medium_armor",
  "heavy_armor",
  "modern_armor",
  "fighter",
  "cas",
  "naval_bomber",
  "tactical_bomber",
  "heavy_fighter",
  "interceptor",
  "scout_plane",
  "suicide",
  "strategic_bomber",
  "cv_fighter",
  "cv_cas",
  "cv_naval_bomber",
  "cv_suicide",
  "cv_interceptor",
  "naval_capital",
  "naval_carrier",
  "naval_screen",
  "naval_sub",
];
